### ISSUE TITLE
Alternative input methods

### ISSUE THREAD

**Issue by luckasRanarison** [luckasRanarison/japidic#4]
- [x] Romaji to kana conversion
- [x] Autocomplete using jotoba APIs
- [x] Kanji by radicals (KRAD or jotoba APIs?)
- [ ] Handwriting
